// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet03_webapi.Models;

#nullable disable

namespace dotnet03_webapi.Migrations
{
    [DbContext(typeof(QLNVContext))]
    partial class QLNVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhanVien", b =>
                {
                    b.Property<int>("IdNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNV"));

                    b.Property<bool>("gioiTinh")
                        .HasColumnType("bit");

                    b.Property<decimal>("luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("maPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("tenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNV");

                    b.HasIndex("maPhongBan");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("PhongBan", b =>
                {
                    b.Property<int>("maPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maPhongBan"));

                    b.Property<string>("diaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("maPhongBan");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("NhanVien", b =>
                {
                    b.HasOne("PhongBan", "phongban")
                        .WithMany("nhanViens")
                        .HasForeignKey("maPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("phongban");
                });

            modelBuilder.Entity("PhongBan", b =>
                {
                    b.Navigation("nhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
